### ISSUE TITLE
main_target_list build error -- GQuest Extended Time.

### ISSUE THREAD

**Issue by zepfu** [AardStarling/Search-and-Destroy-v3.0#3]
When a Gquest goes into extended time, target list is lost.

For example, killing a target mob after initial Gquest winner-- the subsequent display results in error message. 

k r
*[1] Your pound -=- VAPORIZES -=- a rabbit! [112]
A rabbit crumbles as it is battered to death!!
You have 4 daily blessing bonus experience kills remaining.
Congratulations, that was one of the GLOBAL QUEST mobs!
3 quest points awarded.
You can be rewarded for 97 more global quest kills this level.
You get 6 gold coins from the battered corpse of a rabbit.
You get a rabbit's bite from the battered corpse of a rabbit.

You may win 3 more gquests at this level.
You can be rewarded for 97 more kills this level.
main_target_list build error - tried to run while on gq but area/room type is 'none'.
   No target items to show.

A manual 'gquest check', shows targets are still available. 
gquest check
You still have to kill 1 * a bad apple (Gallows Hill)
You still have to kill 2 * a rabbit (Old Farm Lane)
You still have to kill 3 * a tiny, brown mouse (An old dirt path)
You still have to kill 3 * a small earthworm (Pathway around the academy)
You still have to kill 1 * a marbled salamander (Standing Upon Some Stepping Stones)
You still have to kill 1 * a quickling (Northern Woods)
You still have to kill 1 * a pilgrim (The Path of the Believer)
You still have to kill 1 * a weasel (Tournament Camps)
You may win 3 more gquests at this level.
You can be rewarded for 97 more kills this level.

**Comment by zepfu** [comment]
Finally had a chance to dig into this more tonight, looks like 'trg_gqmsg_extended_time' is expecting the gquest to be extended for 3 minutes. While the gquest is infact being extended for 5 (see below). 

I've altered my local and am testing that on the next gquest I can join and fail to win. 

<trigger match="^Global Quest: Global Quest # (?<gq_id>\d{1,4}) will go into extended time for 3 more minutes\.$"
		script="gqmsg_extended_time"
		name="trg_gqmsg_extended_time" 		group="trg_gqmsg_ext"
		enabled="n"	regexp="y" sequence="100" keep_evaluating="y" send_to="12" > </trigger>
vs
<trigger match="^Global Quest: Global Quest # (?<gq_id>\d{1,4}) will go into extended time for 5 more minutes\.$"
		script="gqmsg_extended_time"
		name="trg_gqmsg_extended_time" 		group="trg_gqmsg_ext"
		enabled="n"	regexp="y" sequence="100" keep_evaluating="y" send_to="12" > </trigger>.

**Comment by AardStarling** [comment]
Good morning,

I fixed the issue with gq extended time now being 5 minutes.  Hopefully it works now but if not let me know.  Thanks for helping me by reporting the issue.  If you need anything else please let me know !
